# btop - Dragon Fire
theme[main_bg]=""
theme[main_fg]="#faece8"
theme[title]="#faece8"
theme[hi_fg]="#f5796b"
theme[selected_bg]="#422834"
theme[selected_fg]="#f5796b"
theme[inactive_fg]="#96747b"
theme[graph_text]="#dec7c1"
theme[meter_bg]="#24151b"
theme[proc_misc]="#6fb0a6"

theme[cpu_box]="#573544"
theme[mem_box]="#573544"
theme[net_box]="#573544"
theme[proc_box]="#573544"
theme[div_line]="#573544"

theme[temp_start]="#7ea66b"
theme[temp_mid]="#e89f5a"
theme[temp_end]="#e05853"

theme[cpu_start]="#e89f5a"
theme[cpu_mid]="#f5796b"
theme[cpu_end]="#dc82a6"

theme[free_start]="#415753"
theme[free_mid]="#6fb0a6"
theme[free_end]="#85c7bd"

theme[cached_start]="#476085"
theme[cached_mid]="#688dc4"
theme[cached_end]="#82a5dc"

theme[available_start]="#8c5d31"
theme[available_mid]="#e89f5a"
theme[available_end]="#f5b373"

theme[used_start]="#8c332e"
theme[used_mid]="#e05853"
theme[used_end]="#ff4a5d"

theme[download_start]="#8c473b"
theme[download_mid]="#f5796b"
theme[download_end]="#f5b373"

theme[upload_start]="#80415a"
theme[upload_mid]="#c76d91"
theme[upload_end]="#dc82a6"

theme[process_start]="#7ea66b"
theme[process_mid]="#94bc80"
theme[process_end]="#e89f5a"
