# btop - Nordic Frost
theme[main_bg]=""
theme[main_fg]="#e8eff7"
theme[title]="#e8eff7"
theme[hi_fg]="#68a6d4"
theme[selected_bg]="#2d3e54"
theme[selected_fg]="#68a6d4"
theme[inactive_fg]="#7d93ab"
theme[graph_text]="#c8d8e8"
theme[meter_bg]="#182330"
theme[proc_misc]="#5ec0be"

theme[cpu_box]="#3c516c"
theme[mem_box]="#3c516c"
theme[net_box]="#3c516c"
theme[proc_box]="#3c516c"
theme[div_line]="#3c516c"

theme[temp_start]="#56b88e"
theme[temp_mid]="#e5a840"
theme[temp_end]="#d45b65"

theme[cpu_start]="#5a98cf"
theme[cpu_mid]="#68a6d4"
theme[cpu_end]="#ba94ce"

theme[free_start]="#3d5a59"
theme[free_mid]="#5ec0be"
theme[free_end]="#74d4d2"

theme[cached_start]="#41698e"
theme[cached_mid]="#5a98cf"
theme[cached_end]="#78b4e8"

theme[available_start]="#8f6929"
theme[available_mid]="#e5a840"
theme[available_end]="#f2be5c"

theme[used_start]="#853940"
theme[used_mid]="#d45b65"
theme[used_end]="#de505b"

theme[download_start]="#3b6994"
theme[download_mid]="#5a98cf"
theme[download_end]="#78b4e8"

theme[upload_start]="#6e507d"
theme[upload_mid]="#a47eb8"
theme[upload_end]="#ba94ce"

theme[process_start]="#56b88e"
theme[process_mid]="#68cca0"
theme[process_end]="#e5a840"
