# btop - Pirna, sampled from Bernardo Bellotto's Pirna from Sonnenstein Fortress
theme[main_bg]=""
theme[main_fg]="#ede8dc"
theme[title]="#ede8dc"
theme[hi_fg]="#78a6ba"
theme[selected_bg]="#333d40"
theme[selected_fg]="#78a6ba"
theme[inactive_fg]="#828c8a"
theme[graph_text]="#cdc7b7"
theme[meter_bg]="#1f2527"
theme[proc_misc]="#6e9e98"

theme[cpu_box]="#445053"
theme[mem_box]="#445053"
theme[net_box]="#445053"
theme[proc_box]="#445053"
theme[div_line]="#445053"

theme[temp_start]="#7b9456"
theme[temp_mid]="#cca056"
theme[temp_end]="#b8543f"

theme[cpu_start]="#658ea4"
theme[cpu_mid]="#78a6ba"
theme[cpu_end]="#ba94a8"

theme[free_start]="#465856"
theme[free_mid]="#6e9e98"
theme[free_end]="#84b5ae"

theme[cached_start]="#4f6e82"
theme[cached_mid]="#658ea4"
theme[cached_end]="#78a6ba"

theme[available_start]="#7a6238"
theme[available_mid]="#cca056"
theme[available_end]="#dfb56c"

theme[used_start]="#74372a"
theme[used_mid]="#b8543f"
theme[used_end]="#c45842"

theme[download_start]="#466275"
theme[download_mid]="#658ea4"
theme[download_end]="#78a6ba"

theme[upload_start]="#695160"
theme[upload_mid]="#a17b8f"
theme[upload_end]="#ba94a8"

theme[process_start]="#7b9456"
theme[process_mid]="#8ea559"
theme[process_end]="#cca056"
