# btop - Monolith
theme[main_bg]=""
theme[main_fg]="#dff5f0"
theme[title]="#dff5f0"
theme[hi_fg]="#4ec7b0"
theme[selected_bg]="#284452"
theme[selected_fg]="#4ec7b0"
theme[inactive_fg]="#6e9ca0"
theme[graph_text]="#bee5dd"
theme[meter_bg]="#14242c"
theme[proc_misc]="#4ec7b0"

theme[cpu_box]="#355b6c"
theme[mem_box]="#355b6c"
theme[net_box]="#355b6c"
theme[proc_box]="#355b6c"
theme[div_line]="#355b6c"

theme[temp_start]="#56bf9a"
theme[temp_mid]="#d6b565"
theme[temp_end]="#d95f6e"

theme[cpu_start]="#3d9ed6"
theme[cpu_mid]="#4ec7b0"
theme[cpu_end]="#69e0c9"

theme[free_start]="#2e5461"
theme[free_mid]="#4ec7b0"
theme[free_end]="#69e0c9"

theme[cached_start]="#286387"
theme[cached_mid]="#3d9ed6"
theme[cached_end]="#57b4eb"

theme[available_start]="#7d6a36"
theme[available_mid]="#d6b565"
theme[available_end]="#e8ca7d"

theme[used_start]="#823742"
theme[used_mid]="#d95f6e"
theme[used_end]="#e66075"

theme[download_start]="#286991"
theme[download_mid]="#3d9ed6"
theme[download_end]="#57b4eb"

theme[upload_start]="#624975"
theme[upload_mid]="#9b78b5"
theme[upload_end]="#b390cd"

theme[process_start]="#56bf9a"
theme[process_mid]="#6ad9b2"
theme[process_end]="#d6b565"
